<?php
/**
 * Copyright © 2021 Zazmic. All rights reserved.
 */
?>
<?php if ($block->getConfig('country') ==''): ?>
    <div class="page-title-head">
        <div class="col-left img">
            <img src='<?= $block->escapeHtml($block->getViewFileUrl('Zazmic_AmazonMCF::images/amazon_a.png')) ?>'>
        </div>
        <div class="col-right content">
            <h2><?= $block->escapeHtml(__('Multi-Channel Fulfillment')) ?></h2>
            <h5><?= $block->escapeHtml(__('Automate fulfillment of your store orders using Amazon\'s fast,
             reliable fulfillment.')) ?></h5>
        </div>
    </div>

    <div class="page-actions">
        <div class="page-actions-inner">
            <div class="page-actions-buttons">
                <?= $block->getChildHtml() ?>

                <form class="action-element"
                    action="<?= $block->escapeUrl($block->getUrl('*/*/refreshStatistics')) ?>"
                    method="post">
                    <input
                        name="form_key"
                        type="hidden"
                        value="<?= $block->escapeHtmlAttr($block->getFormKey()) ?>"/>
                    <button
                        class="action-primary"
                        id="addStore"
                        type="button"
                        title="<?= $block->escapeHtmlAttr(__('Add Amazon Account')) ?>">
                        <?= $block->escapeHtml(__('Add Amazon Account')) ?>
                    </button>
                </form>
            </div>
        </div>
    </div>
   <script type="text/x-magento-init">
   {
       "*": {
           "add-store": {}
       }
   }
   </script>
    <?php /* else: ?>
    <div class="page-actions">
        <div class="page-actions-inner">
            <div class="page-actions-buttons">
                <?= $block->getChildHtml() ?>
                <?php if ($block->getConfig('spapi_oauth_code') !=''): ?>
                <form class="action-element"
                    action="<?= $block->escapeUrl($block->getUrl('amazonmcf/setup/index')) ?>"
                    method="post">
                    <input
                        name="form_key"
                        type="hidden"
                        value="<?= $block->escapeHtmlAttr($block->getFormKey()) ?>"/>
                    <button
                        class="action-primary"
                        type="submit"
                        title="<?= $block->escapeHtmlAttr(__('Map your Amazon SKUs to Magento Marketplace
                        SKUs Automatically')) ?>">
                        <?= $block->escapeHtml(__('Automap Products')) ?>
                    </button>
                </form>
                <?php endif; ?>
            </div>
        </div>
    </div>
<?php */ endif; ?>
