<?php
/**
 * Copyright © 2021 Zazmic. All rights reserved.
 */
?>
<?php
/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$titleIdHtml = ($block->getTitleId()) ? ' id="' . $block->escapeHtmlAttr($block->getTitleId()) . '"' : '';
$titleClass = ($block->getTitleClass()) ? ' ' . $block->getTitleClass() : '';
$title = $block->getPageTitle();
?>
<?php if (!empty($block->getActiveConnections())): ?>
<div class="page-title-wrapper<?= $block->escapeHtmlAttr($titleClass) ?>">
    <h1 class="page-title"<?= $block->escapeHtml($titleIdHtml) ?>>
        <img src='<?= $block->escapeHtml($block->getViewFileUrl('Zazmic_AmazonMCF::images/amazon_a.png')); ?>'>
        <?= $block->escapeHtml($title) ?>
    </h1>
    <p><?= $block->escapeHtml(__('Map all Magento SKUs that you would like Amazon MCF to fulfill.')) ?>
        <a href="<?= $block->escapeHtml($block->getUrl('amazonmcf/help/index')); ?>">
            <?= $block->escapeHtml(__('Need help?')) ?>
        </a>
    </p>
    <?= $block->getChildHtml() ?>
</div>
<?php else:?>
<div class="page-title-wrapper<?= $block->escapeHtmlAttr($titleClass) ?>">
    <h1 class="page-title"<?= $block->escapeHtml($titleIdHtml)?>>
        <?= $block->escapeHtml($title) ?>
    </h1>
    <?= $block->getChildHtml() ?>
</div>
<?php endif;?>
